const horario = [
  {
    id: 9933,
    materia: "Matematicas",
    profesor: "Juan Perez",
    horario: 1000,
    grado: "3-A",
    salon: "A-1",
    day: "Lunes",
  },
  {
    id: 583,
    materia: "Español",
    profesor: "Juan Perez",
    horario: 1200,
    grado: "3-A",
    salon: "A-1",
    day: "Lunes",
  },
  {
    id: 9932,
    materia: "Ciencias",
    profesor: "Juan Perez",
    horario: 1400,
    grado: "3-A",
    salon: "A-1",
    day: "Lunes",
  },

  {
    id: 3442,
    materia: "Historia",
    profesor: "Juan Perez",
    horario: 1000,
    grado: "3-A",
    salon: "A-1",
    day: "Martes",
  },
  {
    id: 9935,
    materia: "Geografia",
    profesor: "Juan Perez",
    horario: 1200,
    grado: "3-A",
    salon: "A-1",
    day: "Martes",
  },
  {
    id: 9933,
    materia: "Matematicas",
    profesor: "Juan Perez",
    horario: 1000,
    grado: "3-A",
    salon: "A-1",
    day: "Miercoles",
  },
  {
    id: 583,
    materia: "Español",
    profesor: "Juan Perez",
    horario: 1200,
    grado: "3-A",
    salon: "A-1",
    day: "Miercoles",
  },
  {
    id: 9932,
    materia: "Ciencias",
    profesor: "Juan Perez",
    horario: 1400,
    grado: "3-A",
    salon: "A-1",
    day: "Miercoles",
  },

  {
    id: 3442,
    materia: "Historia",
    profesor: "Juan Perez",
    horario: 1000,
    grado: "3-A",
    salon: "A-1",
    day: "Jueves",
  },
  {
    id: 9935,
    materia: "Geografia",
    profesor: "Juan Perez",
    horario: 1200,
    grado: "3-A",
    salon: "A-1",
    day: "Jueves",
  },
  {
    id: 9933,
    materia: "Matematicas",
    profesor: "Juan Perez",
    horario: 1000,
    grado: "3-A",
    salon: "A-1",
    day: "Viernes",
  },
  {
    id: 583,
    materia: "Español",
    profesor: "Juan Perez",
    horario: 1200,
    grado: "3-A",
    salon: "A-1",
    day: "Viernes",
  },
];
